# Purpose: contains the tests for the model of the best QR code generator application.
# Authors: Bryan Crombach


from PyQt6.QtGui import QImage


class TestModel:
    """
    Class that contains all the tests for the model of the best QR code generator application.
    """

    def test_create_qr_code(self, sample_qr_code) -> None:
        """
        Test the create_qr_code function to ensure it generates a valid QR code image.

        assertions:
        - The generated QR code image is not None.
        - The generated QR code image is not null (i.e., it contains valid image data).
        - The generated QR code image is an instance of QImage.
        - The generated QR code image has a width greater than 0.
        - The generated QR code image has a height greater than 0.
        - The generated QR code image is square (i.e., width equals height).

        :param sample_qr_code: the sample QR code image generated by the fixture.
        :return: None.
        """
        assert sample_qr_code is not None
        assert not sample_qr_code.isNull()
        assert isinstance(sample_qr_code, QImage)
        assert sample_qr_code.width() > 0
        assert sample_qr_code.height() > 0
        assert sample_qr_code.height() == sample_qr_code.width()
