name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dev dependencies
      run: uv sync --dev

    - name: Run check
      run: uv run ruff check . --output-format=github

    - name: Run format
      run: uv run ruff format . --check



