name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync --dev

    - name: install virtual display
      run: sudo apt-get install -y xvfb

    - name: start tests
      run: xvfb-run uv run pytest -v --tb=short --color=yes